# Generated by Django 5.0.4 on 2024-04-12 11:23

import app.models.carPic
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.carPic.upload_image_fomater)),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='pic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.carpic'),
            preserve_default=False,
        ),
    ]
